#ifndef REALISTIC_EXTENSION_CONSTANT_H
#define REALISTIC_EXTENSION_CONSTANT_H

#define Y_COORDINATE_MAX 75.0
#define Y_COORDINATE_MIN -75.0

#define X_COORDINATE_MAX 100.0
#define X_COORDINATE_MIN -50.0

#define X_COORDINATE_SHIFT 0.08

const double RE_PI = 3.141592654;


#endif